### ISSUE TITLE
Data extractor

### ISSUE THREAD

**Issue by Draxinusom** [hankmorgan/UnderworldGodot#1]
Hi, this isn't an issue, I just figured this would probably be the best way to contact you.

Anyhow, I've been working on an [extractor](https://github.com/Draxinusom/UWXtract) for Ultima Underworld 1/2 data/images as sort of a side project for a few months now that I thought may be at a point that it could be of some use to you in your work.  Most of the data it extracts is based on yours or Underworld Adventure's research but I've managed to figure out a few odds and ends that may be helpful.

Hope it helps and thanks again for your work on this, it's been crucial in my efforts and greatly appreciated!

**Comment by hankmorgan** [comment]
Very cool to see. One comment to make. Most of the formats were decoded by the teams that worked on the earlier projects. I can take very little credit for their work.
